

class Solution {

    class TrieNode {
            TrieNode[] children = new TrieNode[26];
                    String word;
                        }

                            TrieNode root = new TrieNode();
                                List<String> result = new ArrayList<>();

                                    public List<String> findWords(char[][] board, String[] words) {

                                            // Build Trie
                                                    for (String word : words) {
                                                                insert(word);
                                                                        }

                                                                                // DFS from every cell
                                                                                        for (int i = 0; i < board.length; i++) {
                                                                                                    for (int j = 0; j < board[0].length; j++) {
                                                                                                                    dfs(board, i, j, root);
                                                                                                                                }
                                                                                                                                        }

                                                                                                                                                return result;
                                                                                                                                                    }

                                                                                                                                                        private void insert(String word) {

                                                                                                                                                                TrieNode current = root;

                                                                                                                                                                        for (char c : word.toCharArray()) {

                                                                                                                                                                                    int index = c - 'a';

                                                                                                                                                                                                if (current.children[index] == null) {
                                                                                                                                                                                                                current.children[index] = new TrieNode();
                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                        current = current.children[index];
                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                        current.word = word;
                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                private void dfs(char[][] board, int row, int col, TrieNode node) {

                                                                                                                                                                                                                                                                        // Boundary check
                                                                                                                                                                                                                                                                                if (row < 0 || row >= board.length ||
                                                                                                                                                                                                                                                                                            col < 0 || col >= board[0].length) {
                                                                                                                                                                                                                                                                                                        return;
                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                        // Already visited
                                                                                                                                                                                                                                                                                                                                if (board[row][col] == '#') {
                                                                                                                                                                                                                                                                                                                                            return;
                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                            char ch = board[row][col];

                                                                                                                                                                                                                                                                                                                                                                    TrieNode next = node.children[ch - 'a'];

                                                                                                                                                                                                                                                                                                                                                                            // Character doesn't continue any word
                                                                                                                                                                                                                                                                                                                                                                                    if (next == null) {
                                                                                                                                                                                                                                                                                                                                                                                                return;
                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                // Complete word found
                                                                                                                                                                                                                                                                                                                                                                                                                        if (next.word != null) {
                                                                                                                                                                                                                                                                                                                                                                                                                                    result.add(next.word);

                                                                                                                                                                                                                                                                                                                                                                                                                                                // Avoid duplicate words
                                                                                                                                                                                                                                                                                                                                                                                                                                                            next.word = null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Mark visited
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    board[row][col] = '#';

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Down
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    dfs(board, row + 1, col, next);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Up
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    dfs(board, row - 1, col, next);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Right
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    dfs(board, row, col + 1, next);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Left
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    dfs(board, row, col - 1, next);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Restore
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    board[row][col] = ch;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }